/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],

  // But you can create a sidebar manually
  melodiSidebar: [
    {
      type: 'link',
      label: '🏠[HOME]🏠',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: 'shaders/melodi'
    }
  ],

  glassrefSidebar: [
    {
      type: 'link',
      label: '🏠[HOME]🏠',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: 'shaders/glassref'
    }
  ],

  unlitstSidebar: [
    {
      type: 'link',
      label: '🏠[HOME]🏠',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: 'shaders/unlitst'
    }
  ],

  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
